### ISSUE TITLE
[Feature] Motion Sensor / Occupancy Sensor

### ISSUE THREAD

**Issue by rderimay** [Sunoo/homebridge-octoprint-motion#1]
Hi there,

thanks for the great work on this plugin !
Publishing octoprint as a motion sensor does imo limit the automation possibilities. 
Let say you have 2 printers and a connected led strip that illuminate both of them, you can not make any useful automation. 
To me it seems that the occupancy sensor variant would solve this problem. We could add automations like "As long as the job is running"

Would be interested in reading what do you think about this. Possibly, we want to let the user select between the one or the other variant. I did not take a look to your code, but I presume, that should be pretty simple ??

**Comment by Sunoo** [comment]
I’ll look into it. I have not dome anything with occupancy sensors, but I expect they work very similarly. I’m working on fixing a few of my plugins that broke under Homebridge 1.0, so this will likely need to wait until after that. I don’t see any obvious issues with your idea though.

**Comment by rderimay** [comment]
Excellent. I can look into it on a fork. (Never did any octoprint plugin :-D)
Do you pull the state for octoprint with the help of a timer, or do you register a callback in octoprint to get messaged on changes ?

**Comment by Sunoo** [comment]
I open a SockJS connection and wait for events from Octoprint. I believe my code is fairly readable, but I’m happy to assist where possible.

And if you do a fork, I’m more than happy to accept a pull request from it if you get it going before I do.

**Comment by rderimay** [comment]
Ill look at it today. Your code is absolutely readable :-)

**Comment by Sunoo** [comment]
I've added this feature. To use it just set `occupancy_sensor` to `true` in your config. The default will still be to expose a motion sensor, so as not to break any existing users.

**Comment by rderimay** [comment]
> I've added this feature. To use it just set `occupancy_sensor` to `true` in your config. The default will still be to expose a motion sensor, so as not to break any existing users.

Excellent! I did not find the time to look into it. Thanks!

**Comment by Sunoo** [comment]
You’re welcome. I found myself with some free time and some energy, and it turned out to be a fairly simple change.
