### ISSUE TITLE
Battery Charge Level = 0%.

### ISSUE THREAD

**Issue by BengalPrint** [Sunoo/homebridge-octoprint-motion#50]
Can we have the battery level updated to 100% so a fault isn't shown in homekit for low battery?

**Comment by Sunoo** [comment]
Low battery status is controlled separately from the battery level. I use the low battery status to report on fault conditions, such as not being able to connect to your Octoprint instance. Battery level is used to show progress of the print, and if I remember correctly, it does default to 100% when no print is in progress.

**Comment by BengalPrint** [comment]
Sorry for the crappost. I just realized I'm actually have trouble connecting.

**Comment by Sunoo** [comment]
No worries, I’ll close this out then.
